load("00_tools/CPAT-1.2.4/dat/Mouse_logitModel.RData")
test <- read.table(file="05_CPAT/01_output/RB_CPAT.txt.dat",sep="\t",col.names=c("ID","mRNA","ORF","Fickett","Hexamer"))
test$prob <- predict(mylogit,newdata=test,type="response")
attach(test)
output <- cbind("mRNA_size"=mRNA,"ORF_size"=ORF,"Fickett_score"=Fickett,"Hexamer_score"=Hexamer,"coding_prob"=test$prob)
write.table(output,file="05_CPAT/01_output/RB_CPAT.txt",quote=F,sep="\t",row.names=ID)
